use axum::{extract::State, Json};
use serde::Deserialize;
use serde_json::json;
use std::sync::Arc;
use uuid::Uuid;

use crate::errors::AppError;
use crate::state::AppState;

#[derive(Debug, Deserialize)]
pub struct VerifyAttestationRequest {
    /// Client device identifier (UUIDv4).
    pub device_id: Uuid,
    /// Base64-encoded keyId generated by the device.
    pub key_id: String,
    /// Base64-encoded CBOR attestation object from Apple App Attest.
    pub attestation: String,
    /// Hex-encoded challenge nonce that was verified.
    pub challenge: String,
}

#[derive(Debug, Deserialize)]
pub struct AssertRequest {
    /// Client device identifier.
    pub device_id: Uuid,
    /// Base64-encoded CBOR assertion object from Apple App Attest.
    pub assertion: String,
    /// Hex-encoded challenge nonce.
    pub challenge: String,
    /// Hex-encoded SHA-256 hash of the request body (clientDataHash components).
    pub request_body_hash: String,
}

/// Handler for `GET /api/v1/auth/challenge`.
/// Generates a single-use cryptographically random challenge.
pub async fn challenge_handler(
    State(state): State<Arc<AppState>>,
) -> Result<Json<serde_json::Value>, AppError> {
    let challenge = state.nonce_cache.generate_nonce()?;
    Ok(Json(json!({ "challenge": challenge })))
}

/// Handler for `POST /api/v1/auth/verify-attestation`.
/// Cryptographically verifies Apple App Attest attestation and registers the device.
pub async fn verify_attestation_handler(
    State(state): State<Arc<AppState>>,
    Json(payload): Json<VerifyAttestationRequest>,
) -> Result<Json<serde_json::Value>, AppError> {
    // 1. Consume the nonce from cache to enforce single-use replay protection
    state.nonce_cache.verify_and_consume(&payload.challenge)?;

    // 2. Cryptographically verify the attestation object
    let verified = crate::crypto::attestation::verify_attestation(
        &state.config,
        &payload.attestation,
        &payload.challenge,
        &payload.key_id,
    )?;

    // 3. Register/persist the device details in the database
    let new_device = crate::models::device::AttestedDevice {
        device_id: payload.device_id,
        public_key_der: verified.public_key_der,
        sign_counter: 0,
        registered_at: chrono::Utc::now(),
    };
    state.db.insert_device(&new_device).await?;

    // 4. Generate a session token for post-attestation API access
    let token = crate::crypto::session::create_session_token(
        &state.hmac_key,
        payload.device_id,
        state.config.auth.session_token_ttl_seconds,
    )?;

    Ok(Json(json!({
        "status": "verified",
        "token": token
    })))
}

/// Handler for `POST /api/v1/auth/assert`.
/// Performs login/session refresh by verifying client assertion token.
pub async fn assert_handler(
    State(state): State<Arc<AppState>>,
    Json(payload): Json<AssertRequest>,
) -> Result<Json<serde_json::Value>, AppError> {
    // 1. Consume the challenge nonce from the cache
    state.nonce_cache.verify_and_consume(&payload.challenge)?;

    // 2. Fetch the registered device from database
    let device = state
        .db
        .get_device(payload.device_id)
        .await?
        .ok_or(AppError::DeviceNotFound)?;

    // 3. Cryptographically verify assertion signature and counter
    let verified = crate::crypto::assertion::verify_assertion(
        &state.config,
        &payload.assertion,
        &payload.challenge,
        &payload.request_body_hash,
        &device.public_key_der,
        device.sign_counter,
    )?;

    // 4. Persist updated sign counter
    state
        .db
        .update_counter(payload.device_id, verified.new_counter)
        .await?;

    // 5. Issue a new session token
    let token = crate::crypto::session::create_session_token(
        &state.hmac_key,
        payload.device_id,
        state.config.auth.session_token_ttl_seconds,
    )?;

    Ok(Json(json!({
        "status": "valid",
        "new_counter": verified.new_counter,
        "token": token
    })))
}
