use axum::{extract::State, Json};
use serde::Deserialize;
use serde_json::json;
use std::sync::Arc;
use uuid::Uuid;

use crate::errors::AppError;
use crate::state::AppState;

#[derive(Debug, Deserialize)]
pub struct VerifyAttestationRequest {
    /// Client device identifier (`UUIDv4`).
    pub device_id: Uuid,
    /// Base64-encoded keyId generated by the device.
    pub key_id: String,
    /// Base64-encoded CBOR attestation object from Apple App Attest.
    pub attestation: String,
    /// Hex-encoded challenge nonce that was verified.
    pub challenge: String,
}

#[derive(Debug, Deserialize)]
pub struct AssertRequest {
    /// Client device identifier.
    pub device_id: Uuid,
    /// Base64-encoded CBOR assertion object from Apple App Attest.
    pub assertion: String,
    /// Hex-encoded challenge nonce.
    pub challenge: String,
    /// Hex-encoded SHA-256 hash of the request body (clientDataHash components).
    pub request_body_hash: String,
}

/// Handler for `GET /api/v1/auth/challenge`.
/// Generates a single-use cryptographically random challenge.
#[tracing::instrument(skip(state))]
pub async fn challenge_handler(
    State(state): State<Arc<AppState>>,
) -> Result<Json<serde_json::Value>, AppError> {
    metrics::counter!("antigravity_api_requests_total", "endpoint" => "/auth/challenge")
        .increment(1);
    let challenge = state.nonce_cache.generate_nonce()?;
    Ok(Json(json!({ "challenge": challenge })))
}

/// Handler for `POST /api/v1/auth/verify-attestation`.
/// Cryptographically verifies Apple App Attest attestation and registers the device.
#[tracing::instrument(skip(state, payload), fields(device_id = %payload.device_id))]
pub async fn verify_attestation_handler(
    State(state): State<Arc<AppState>>,
    Json(payload): Json<VerifyAttestationRequest>,
) -> Result<Json<serde_json::Value>, AppError> {
    metrics::counter!("antigravity_api_requests_total", "endpoint" => "/auth/verify-attestation")
        .increment(1);
    let start_time = std::time::Instant::now();

    // 1. Consume the nonce from cache to enforce single-use replay protection
    state.nonce_cache.verify_and_consume(&payload.challenge)?;

    // 2. Cryptographically verify the attestation object
    let verified = crate::crypto::attestation::verify_attestation(
        &state.config,
        &payload.attestation,
        &payload.challenge,
        &payload.key_id,
    )?;

    // 3. Register/persist the device details in the database
    let new_device = crate::models::device::AttestedDevice {
        device_id: payload.device_id,
        public_key_der: verified.public_key_der,
        sign_counter: 0,
        registered_at: chrono::Utc::now(),
    };
    let db_start = std::time::Instant::now();
    state.db.insert_device(&new_device).await?;
    metrics::histogram!("antigravity_db_latency_seconds", "operation" => "insert_device")
        .record(db_start.elapsed().as_secs_f64());

    // 4. Generate a session token for post-attestation API access
    let token = crate::crypto::session::create_session_token(
        &state.hmac_key,
        payload.device_id,
        state.config.auth.session_token_ttl_seconds,
    )?;

    // 5. Audit log registration event
    state
        .db
        .insert_audit_log("REGISTER_DEVICE", payload.device_id, payload.device_id, &[])
        .await?;

    metrics::histogram!("antigravity_request_duration_seconds", "endpoint" => "/auth/verify-attestation").record(start_time.elapsed().as_secs_f64());

    Ok(Json(json!({
        "status": "verified",
        "token": token
    })))
}

#[derive(Debug, Deserialize)]
pub struct DevSessionRequest {
    /// Client device identifier. Reusing the same id across calls keeps the
    /// same dev identity (and its game profile / subscription / documents).
    pub device_id: Uuid,
    /// Optional base64 raw uncompressed P-256 public key (65 bytes, `0x04…`).
    /// When supplied, the device is registered with this key so the client can
    /// produce *real* ECDSA signatures on sync payloads — the web app does
    /// this via `WebCrypto`, making its E2EE flow cryptographically identical
    /// to the native client's.
    #[serde(default)]
    pub public_key: Option<String>,
}

/// Handler for `POST /api/v1/auth/dev-session`.
///
/// **Development-only** session mint for clients that cannot perform Apple
/// App Attest (the browser app, local tooling). Registers the device with a
/// synthetic per-device key and issues a normal session token, so every
/// protected endpoint works end-to-end in local development.
///
/// Hard-gated on `auth.environment == "development"`: in any other
/// environment it returns 404-equivalent `DeviceNotFound`-free 403 via
/// `Forbidden`, and the router still requires real attestation.
#[tracing::instrument(skip(state, payload), fields(device_id = %payload.device_id))]
pub async fn dev_session_handler(
    State(state): State<Arc<AppState>>,
    Json(payload): Json<DevSessionRequest>,
) -> Result<Json<serde_json::Value>, AppError> {
    metrics::counter!("antigravity_api_requests_total", "endpoint" => "/auth/dev-session")
        .increment(1);

    if state.config.auth.environment != "development" {
        return Err(AppError::Forbidden(
            "Dev sessions are disabled outside the development environment.".to_owned(),
        ));
    }

    // Use the client's real P-256 key when it sends one (so its ECDSA sync
    // signatures verify), otherwise fall back to a synthetic key derived from
    // the device id: stable across calls for the same device (idempotent
    // re-registration) and unique per device (the takeover guard still holds
    // between dev identities).
    let public_key_der = match &payload.public_key {
        Some(b64) => {
            use base64::Engine as _;
            let key = base64::prelude::BASE64_STANDARD.decode(b64)?;
            if key.len() != 65 || key[0] != 0x04 {
                return Err(AppError::BadRequest(
                    "public_key must be a 65-byte uncompressed P-256 point".to_owned(),
                ));
            }
            key
        }
        None => {
            let mut key = vec![0x04u8];
            key.extend_from_slice(payload.device_id.as_bytes());
            key.resize(65, 0xDE);
            key
        }
    };

    state
        .db
        .insert_device(&crate::models::device::AttestedDevice {
            device_id: payload.device_id,
            public_key_der,
            sign_counter: 0,
            registered_at: chrono::Utc::now(),
        })
        .await?;

    let token = crate::crypto::session::create_session_token(
        &state.hmac_key,
        payload.device_id,
        state.config.auth.session_token_ttl_seconds,
    )?;

    state
        .db
        .insert_audit_log("DEV_SESSION", payload.device_id, payload.device_id, &[])
        .await?;

    Ok(Json(json!({
        "status": "dev",
        "token": token,
        "expires_in": state.config.auth.session_token_ttl_seconds,
    })))
}

/// Handler for `POST /api/v1/auth/assert`.
/// Performs login/session refresh by verifying client assertion token.
#[tracing::instrument(skip(state, payload), fields(device_id = %payload.device_id))]
pub async fn assert_handler(
    State(state): State<Arc<AppState>>,
    Json(payload): Json<AssertRequest>,
) -> Result<Json<serde_json::Value>, AppError> {
    metrics::counter!("antigravity_api_requests_total", "endpoint" => "/auth/assert").increment(1);
    let start_time = std::time::Instant::now();

    // 1. Consume the challenge nonce from the cache
    state.nonce_cache.verify_and_consume(&payload.challenge)?;

    // 2. Fetch the registered device from database
    let db_start = std::time::Instant::now();
    let device = state
        .db
        .get_device(payload.device_id)
        .await?
        .ok_or(AppError::DeviceNotFound)?;
    metrics::histogram!("antigravity_db_latency_seconds", "operation" => "get_device")
        .record(db_start.elapsed().as_secs_f64());

    // 3. Cryptographically verify assertion signature and counter
    let verified = crate::crypto::assertion::verify_assertion(
        &state.config,
        &payload.assertion,
        &payload.challenge,
        &payload.request_body_hash,
        &device.public_key_der,
        device.sign_counter,
    )?;

    // 4. Persist updated sign counter
    let db_start = std::time::Instant::now();
    state
        .db
        .update_counter(payload.device_id, verified.new_counter)
        .await?;
    metrics::histogram!("antigravity_db_latency_seconds", "operation" => "update_counter")
        .record(db_start.elapsed().as_secs_f64());

    // 5. Issue a new session token
    let token = crate::crypto::session::create_session_token(
        &state.hmac_key,
        payload.device_id,
        state.config.auth.session_token_ttl_seconds,
    )?;

    // 6. Audit log assertion/login event
    state
        .db
        .insert_audit_log(
            "VERIFY_ASSERTION",
            payload.device_id,
            payload.device_id,
            &[],
        )
        .await?;

    metrics::histogram!("antigravity_request_duration_seconds", "endpoint" => "/auth/assert")
        .record(start_time.elapsed().as_secs_f64());

    Ok(Json(json!({
        "status": "valid",
        "new_counter": verified.new_counter,
        "token": token
    })))
}
